module.exports = {
    REPORT_CREATED: 10,
    ISSUE_VERIFIED: 20,
    UPVOTE_RECEIVED: 1,
    ISSUE_REJECTED: -20,
    MIN_REPUTATION_TO_REPORT: -10,
    MIN_REPUTATION_TO_COMMENT: -15,
    MIN_REPUTATION_TO_VOTE: -20
};